### ISSUE TITLE
requesting a GHIDRA 10.4 build

### ISSUE THREAD

**Issue by modusc896d352** [XboxDev/ghidra-xbe#56]
i'm currently using GHIDRA 10.4 and i'd like to use this extension with this new version
of course, i could compile it myself but i don't have enough time to do that

**Comment by modusc896d352** [comment]
i lied

compiling this whole thing into a build that's compatible with GHIDRA 10.4 was actually rather easy if you don't go for just executing build.sh, so instead i'll just describe what i did by way of outlining them into actual steps.

**Step1**
invoke command-line prompt on your OS (mine is Windows 10)

**Step2**
locate the folder of the entire source code of this thing, like this
```
C:\ghidra-xbe
```
`C:\ghidra-xbe` is just an example and represents said folder.

**Step3**
once you're done, type "cd" then type the whole name of the folder, like this
```
cd C:\ghidra-xbe
```

**Step4**
after that, type this out
```
gradle build
```
if you have GHIDRA_INSTALL_DIR set as *the* environment variable on your OS, this step will work flawlessly so skip to step6, otherwise skip to step5.

**Step5**
if you already have GHIDRA_INSTALL_DIR set on your OS then you don't need to perform this step at all, but again proceed to step6.

anyway, after step3, type this out
```
gradle -PGHIDRA_INSTALL_DIR="C:\path\to\ghidra_installation"
```
(the quotes are there for precaution sake, if the entire name of the path (which can include dozens of folders in it by the way) contains even one space then you need the quotes, but for now just drag-and-drop the whole thing into the command-line AFTER the = symbol shown above)

`C:\path\to\ghidra_installation` represents the folder of an entire GHIDRA installation.

**Step6**
your compiled build is in the "dist" folder of said source code folder, like this
```
C:\ghidra-xbe\dist
```
in it you'll find a zip file containing said build.

**Step7**
uhhhhhhh that's it i guess

anyway, that'll be it for me from now, but in the meantime, here's the compiled build!
[ghidra_10.4_PUBLIC_20231031_ghidra-xbe-master.zip](https://github.com/XboxDev/ghidra-xbe/files/13223020/ghidra_10.4_PUBLIC_20231031_ghidra-xbe-master.zip)

**Comment by mborgerson** [comment]
Please send a PR, then a release will be auto generated when it's merged

**Comment by modusc896d352** [comment]
done.
