### ISSUE TITLE
Failed to run XbSymbolDatabaseTool" error upon analysis.

### ISSUE THREAD

**Issue by databoose** [XboxDev/ghidra-xbe#67]
### I am re opening this issue as i believe this is could be a bug.

Here is my include setup for the headers :
![image](https://github.com/user-attachments/assets/fdbe289f-5e2a-4afa-b960-04989b802bcc)

The documentation says  " In the Data Type Manager window, right click on your default.xbe and select Apply Function Datatypes."

Once i do this, this error shows up. The same also happens during analysis.

![image](https://github.com/user-attachments/assets/dc6edb85-4dc5-4122-949d-95ce4e01b156)

The build process does chmod +x XbSymbolDatabaseTool properly, and when i had checked, the file had already been set to executable.

**OP's workaround on the original issue thread did not work for me.**, so i figured this should be investigated further.

Upon looking through ghidra user debug logs, i could find nothing actually referrencing XBSymbolDatabaseTool to maybe get an idea as to what is going on, so my next step was to download the source of this repo and grep the string.

![image](https://github.com/user-attachments/assets/27975777-8fad-413b-89c0-692ccd402c6b)

Essentially, to my understanding at least, XbSymbolDatabaseTool is within the following file : 

https://github.com/XboxDev/ghidra-xbe/blob/master/src/main/java/XbeLoader/XbeXbSymbolDatabaseAnalyzer.java

In the following code here, starting from line 123 , some type of exception is caught, and thus this exact error message is displayed (i could not find an occurence of this error message anywhere else within the entire repo, so pretty sure we narrowed it down here)

I presume perhaps this is a configuration error or some type of ghidra issue, but i thought this would be important enough to re-open as an issue.

```java    
                } catch (InterruptedException e) {
			log.appendMsg("Failed to run " + toolExec);
			return false;
		} catch (IOException e) {
			log.appendMsg("Failed to run " + toolExec);
			return false;
		} catch (InvalidInputException e) {
			log.appendMsg("Failed to run " + toolExec);
			return false;
               }

**Comment by RadWolfie** [comment]
Hi there, can you check your currently installed Ghidra's "Extensions" folder to verify the XBSymbolDatabaseTool binary do exist? The information to find your installed Extension folder can be found on [Ghidra's Installation Guide](https://ghidra-sre.org/InstallationGuide.html#GhidraExtensionNotes).

If they do exist with permission applied correctly (for double check purpose). Then you may want to manually run XBSymbolDatabaseTool on your preferred terminal to find out if the cli tool do output error.

**Comment by RadWolfie** [comment]
> Yes, the XbSymbolDatabaseTool does exist, under /ghidra_11.1.2_PUBLIC/Extensions/ghidra-xbe/os/linux_x86_64/

Okay, the next thing I can think of is xbe you had imported xbe's original file either got moved or no longer exist. If this is not the issue, then I have no idea what may be the cause at this time.

> Now, i tried importing the project in intellij and building it to perhaps debug in runtime, however i am encountering a build issue.
> 
> `/home/databoose/Desktop/external-projects/ghidra-xbe/src/main/java/XbeLoader/XbeXtlidAnalyzer.java:60: error: package XbeXtlidDb does not exist String[] name_namespace = XbeXtlidDb.xtlids.get(id);`

Please verify if you have installed `xsltproc` on your operating system. It is part of the requirement for generate `XbeXtlidDb.java` file. Then run build.sh script again, hopefully this will resolve your issue. Apologizes if it's still not working, I'm not native to Linux operating systems. Except I do use GitHub's workspace to build ghidra-xbe which require xsltproc to be installed before able to successfully generate `XbeXtlidDb.java` file.

> In the following code here, starting from line 123 , some type of exception is caught, and thus this exact error message is displayed (i could not find an occurence of this error message anywhere else within the entire repo, so pretty sure we narrowed it down here)

Yes, that is where the fault occurred. Except it doesn't include depth information about the cause of crash. Hopefully someday, we will have more details about the cause of crash.

**Comment by databoose** [comment]
> Please verify if you have installed `xsltproc` on your operating system. It is part of the requirement for generate XbeXtlidDb.java file. Then run build.sh script again, hopefully this will resolve your issue. 

Installing this package on my system, then rebuilding with the build.sh file resolves the issue fully for me, no error when applying function types, or (just to make sure), no error during the entirety of ghidra's analysis.

Perhaps have a check for this package during the build.sh script execution, although my system is debian-based and the package names differ from debian to arch (debian-based  for me, so it is `xsltproc` but on arch-based it would be `libxslti`, i might be able to make a PR that adds in a check for this package if you guy's don't mind.

Thank you for the help, much appreciated.

**Comment by RadWolfie** [comment]
Hi @databoose, can you test pull request #73 to verify if the details of the issue are explained enough to figure out the cause of the problem?

**Comment by databoose** [comment]
> Hi @databoose, can you test pull request #73 to verify if the details of the issue are explained enough to figure out the cause of the problem?

@RadWolfie (Apologies for tagging, i'm not sure if replies notify you or if quoting is enough)

So you had made me discover some very strange things today.

I was going to build your PR, however before doing so, i wanted to ensure to remove the `xsltproc` package, so that the error would actually happen obviously, however, 2 things i discovered : 

1. The build script had actually failed this time, telling me that `xsltproc` was not found (line 64 on build.sh),  the thing is, when having this issue originally, i did not have this package installed, so i am very confused why it tells me this is missing now, but didn't at the time of my first post of this issue thread, as i did not have the package installed.

2. However, to workaround this, i installed `xsltproc`, ran build.sh, built just fine, and then i uninstalled `xsltproc` after building, to ensure the error would happen. (i checked my bash history to confirm and infact, i uninstalled `xsltproc` right after building)

... **Now here's thing, the error didn't happen**, neither when applying data types, or neither when analysing, which is what would cause it to error orginally, **i do not have the package installed at all**, **and somehow it (at least seems to) run fine.**

To be clear, i checked bash history and infact i did immediately remove the `xsltproc` package right after building your PR of ghidra-xbe.

So, i am thinking possibly this is something on my end, but this is very bewildering and honestly i have no clue how this works, it shouldn't be working at all in theory but it does. This could perhaps be something happening on my end, i'm not sure.

**Comment by RadWolfie** [comment]
Off topic, the `xsltproc` package is only needed to build ghidra-xbe plugin. End-users do not need to install the package just to install the ghidra-xbe plugin from this repository's [release page](https://github.com/XboxDev/ghidra-xbe/releases). Since it is not relative to XbSymbolDatabaseTool which contains pre-compiled binaries downloaded from Cxbx-Reloaded/XbSymbolDatabase's [release page](https://github.com/Cxbx-Reloaded/XbSymbolDatabase/releases). (Which also doesn't have any dependency to use `xsltproc` package.)

**Comment by databoose** [comment]
> Off topic, the `xsltproc` package is only needed to build ghidra-xbe plugin. End-users do not need to install the package just to install the ghidra-xbe plugin from this repository's [release page](https://github.com/XboxDev/ghidra-xbe/releases). Since it is not relative to XbSymbolDatabaseTool which contains pre-compiled binaries downloaded from Cxbx-Reloaded/XbSymbolDatabase's [release page](https://github.com/Cxbx-Reloaded/XbSymbolDatabase/releases). (Which also doesn't have any dependency to use `xsltproc` package.)
> 
> My current focus is the confusion of why has XbSymbolDatabaseTool failed to run for you. Hence the pull request was created to extend the details of the cause of failure.

Ah that makes sense, thanks for the clarification.

As for the actual `XbSymbolDatabaseTool` error, yeah, i built yours and it didn't show up any issues for me, which is strange considering your PR only adds additional details to when the exception is caught, which is strange.

Like i said this could perhaps be something on my end? Not sure but your build works great for me, i am just unable to trigger the error to be able to help you out here, apologies.
